# Generated by Django 3.2.2 on 2021-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
